---
title: "git_00"
author: "Matt Diaz"
date: "Spring 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

'Twas brillig, and the slithy toves.   
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,    
And the mome raths outgrabe.    

"Beware the Jabberwock, my son!    
The jaws that bite, the claws that catch!    
Beware the Jubjub bird, and shun.   
The frumious Bandersnatch!"    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

He took his vorpal sword in hand:  
Long time the manxome foe he sought --  
So rested he by the Tumtum tree,  
And stood a while in thought.  

And, as in uffish thought he stood,  
The Jabberwock, with eyes of flame,  
Came whiffling through the tulgey wood,  
And burbled as it came!  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

One two! One two! And through and through.   
The vorpal blade went snicker-snack!    
He left it dead, and with its head.   
He went galumphing back.    

"And hast thou slain the Jabberwock?    
Come to my arms, my beamish boy!    
Oh frabjous day! Callooh! Callay!"    
He chortled in his joy.    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
